sudo: false

os:
  - osx
  - linux

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.1
      - cabal-install-1.22
      - happy
      - alex
      - nodejs
      - npm

env:
  matrix:
    - ELM_VERSION=master TARGET_NODE_VERSION=node
    - ELM_VERSION=master TARGET_NODE_VERSION=0.10
    - ELM_VERSION=0.16 TARGET_NODE_VERSION=node
    - ELM_VERSION=0.16 TARGET_NODE_VERSION=0.10

  global:
    - secure: "RY4A5Bj0tN7rscwPh6eDJUmf2qWW6lXPBQrD74vg3hB1ubloCRuoXvBD8evUSQg6Kb1D7Dqi3FNpZmt9In7Tiz3Xy6Vb4Q0pbh1r8rq97ZuFFbxzPVRL2QuyYuqQfvsfoal4NVxGyhfTaLh1tCC/G6CjCjGDRXFcqhcz+CR0cEI="

before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ];
    then brew update; brew install cabal-install; brew install nvm; mkdir ~/.nvm; export NVM_DIR=~/.nvm; source $(brew --prefix nvm)/nvm.sh; else
    export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH; curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash;
    fi

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - travis_retry cabal update

before_script:
  - if [ ${TRAVIS_OS_NAME} == "osx" ];
    then export BINARY_OS_NAME=darwin; else
    export BINARY_OS_NAME=$TRAVIS_OS_NAME;
    fi
  - cd installers

script:
  - runhaskell BuildFromSource.hs $ELM_VERSION
  - cd Elm-Platform/*
  - mkdir dist_binaries
  - cp .cabal-sandbox/bin/elm* dist_binaries
  - du -hs dist_binaries
  - tar cvzf binaries.tar.gz dist_binaries
  - du -hs binaries.tar.gz
  - curl -T binaries.tar.gz -uelmtravis:$BINTRAY_API_KEY https://api.bintray.com/content/elmlang/elm-platform/npm/$ELM_VERSION/$ELM_VERSION/$BINARY_OS_NAME-x64.tar.gz
  - cd ../..
  - npm install ./npm
  - node_modules/.bin/elm-make --help
  - node_modules/.bin/elm-repl --help
  - node_modules/.bin/elm-package install --help
  - node_modules/.bin/elm-reactor --help
  - node_modules/.bin/elm make --help
  - node_modules/.bin/elm repl --help
  - node_modules/.bin/elm package install --help
  - node_modules/.bin/elm reactor --help
